@startuml
start
:Посетитель выбирает сессию;
:Авторизация в системе;
:Проверка свободных мест;
if (Есть свободные места?) then (да)
    :Заполнение регистрации;
    :Отправка регистрации;
    :Регистрация системой;
else (нет)
    :Показ сообщения "Свободных мест нет";
endif
stop
@enduml
