@startuml
start
:Авторизация билетёра;
:Просмотр новых заявок;
:Выбор заявки;
if (заявка корректна?) then (да)
  :подтверждение заявки;
  :изменение статуса на подтверждено;
  :уменьшение количества свободных мест;
  :уведомление посетителя;
else (нет)
  :отклонение заявки;
  :уведомление посетителя;
endif
stop
@enduml
